extra-package-dbs: []
packages:
- '.'
- 'discord-types'
- 'discord-rest'
- 'discord-gateway'
- location:
    git: https://github.com/mrkkrp/req.git
    commit: 030d75ac3df2e80db15aa5a481b65ddaa41dd8f6
  extra-dep: true
resolver: lts-8.5
nix:
  packages: [ zlib, gmp ]
